version: '3.3'
services:
  db:
    image: mysql:5.6
    container_name: mysql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - 3356:3306
    expose: 
      - "3306"  
    network_mode: host
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: admin
    volumes:
      - /volumes/databases/mysql:/var/lib/mysql
      - ${PWD}/schemas/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    container_name: api-starwars
    build: 
      context: ./
    ports: 
      - 8090:8090
    expose: 
      - "8090"  
    network_mode: host
    restart: always