version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: mysql_starwars
    ports:
      - 3356:3306
    expose: 
      - "3306"  
    network_mode: host
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: admin
    volumes:
      - ${PWD}/volumes:/var/lib/mysql
      - ${PWD}/volumes/schemas/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql

  api:
    container_name: api-starwars
    build:
      context: ./
    ports: 
      - 8090:8090
    expose: 
      - "8090"  
    network_mode: host
    restart: always