version: '3.3'
services:
  db:
    image: mysql:5.6
    container_name: mysql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - 3356:3306
    expose: 
      - "3306"  
    network_mode: host
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: admin
    volumes:
      - ${PWD}/volumes:/var/lib/mysql
      - ${PWD}/volumes/schemas:/docker-entrypoint-initdb.d